name: Parsl

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  main-test-suite:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Non-requirements based install
      run: |
        sudo apt-get update -q
        python --version

        # this is to make the workqueue binary installer happy
        sudo apt-get install -y libpython3.5


        # mpi is required by the radical executor
        sudo apt install -y mpich

    - name: setup virtual env
      run: |
        make virtualenv
        source .venv/bin/activate

    - name: make deps clean_coverage
      run: |
        source .venv/bin/activate
        make deps
        make clean_coverage

    # config_local_test comes after viz so that the large monitoring.db
    # created by `make test` is still around
    - name: make config_local_test
      run: |
        source .venv/bin/activate
        make config_local_test

    - name: Archive runinfo logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: runinfo-${{ matrix.python-version }}
        path: runinfo/
